routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "HomeController@index");
Auth::routes(['verify' => true]);

Route::get('/page/{page}', "HomeController@page")->name('pages');
Route::any('/purchase', 'HomeController@Purchase')->name('purchase');
Route::get('/payment/confirm', 'PaymentController@index')->name('payment.confirm')->middleware('auth');
Route::post('/payment/process', 'PaymentController@process')->name('payment.process')->middleware('auth');
Route::post('/payment/invitation', 'PaymentController@invitation')->name('payment.invitation')->middleware('auth');
Route::get('/payment/confirmation', 'PaymentController@confirmation')->name('payment.confirmation')->middleware('auth');

Route::middleware(['subscribed','auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/access-videos', 'HomeController@access')->name('access-videos');
    Route::get('/access-video/{id}', 'HomeController@accessVideo')->name('access-video');
});

Route::prefix('admin')->group(function(){
    Route::get('', 'AdminController@index');
    Route::resource('page-blocks', 'PageBlockController');
    Route::resource('invites', 'InviteController');
    Route::resource('modules', 'Admin\VideoController');
    Route::resource('users', 'UserController');
    Route::resource('transactions', 'TransactionController');
    Route::resource('activity', 'ActivityController');
    Route::post('complete/activity/{activity}', 'ActivityController@complete')->name('activity.complete');
});

app/Invite.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invite extends Model
{
    public $incrementing = false;
    public function is_accepted()
    {
        if($this->is_accepted){
            return "Accepted";
        }
        else{
            return "Not Accepted";
        }
    }
    public function user()
    {
        return $this->belongsTo("App\User","email","user_email");
    }
}

app/Http/Controllers/InviteController.php
<?php

namespace App\Http\Controllers;

use App\Invite;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Mail;
use App\Mail\InvitationEmail;
class InviteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $invites = Invite::paginate(($request->count)?$request->count:10);
        return view('admin.invites.index',['invites'=>$invites]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $emails = explode(',',$request->emails);
        $validEmails = 0;
        $invalidEmails = 0;
        foreach ($emails as $email) {
            if(filter_var( $email, FILTER_VALIDATE_EMAIL )){
                $invite = Invite::where('user_email',$email)->first();
                if(!$invite){
                    $invite = new Invite;
                    $invite->id = (string) Str::uuid();
                    $invite->user_email = $email;
                    $invite->save();
                    $validEmails++;
                }

                Mail::to($email)->send(new InvitationEmail($invite));

            }
            else{
                $invalidEmails++;
            }
        }
        return redirect()->back()->with('success',"Invited $validEmails Emails");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Invite  $invite
     * @return \Illuminate\Http\Response
     */
    public function show(Invite $invite)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Invite  $invite
     * @return \Illuminate\Http\Response
     */
    public function edit(Invite $invite)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Invite  $invite
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Invite $invite)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Invite  $invite
     * @return \Illuminate\Http\Response
     */
    public function destroy(Invite $invite)
    {
        //
    }
}

resources/views/admin/invites/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="py-4"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="float-right">
                <a href="{{route('page-blocks.index')}}" class="btn btn-dark btn-sm">Back to Pageblocks</a>
            </div>
            <h4>Create Page Block</h4>
        </div>
        <div class="col-sm-12 mt-4">
            <form action="{{route('page-blocks.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="title">Slug</label>
                    <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror" value="{{@old('title')}}">
                    @error('title') 
                        <span class="invalid-feedback">
                            {{$message}}
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea name="content" id="content" class="editor @error('content') is-invalid @enderror">{{@old('content')}}</textarea>
                    @error('content') 
                        <span class="invalid-feedback">
                            {{$message}}
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                 <button type="submit" class="btn btn-success ">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/invites/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="py-4"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="float-right">
                <a href="{{route('page-blocks.index')}}" class="btn btn-dark btn-sm">Back to Pageblocks</a>
            </div>
            <h4>Edit {{$pageblock->title}}</h4>
        </div>
        <div class="col-sm-12 mt-4">
            <form action="{{route('page-blocks.update',$pageblock)}}" method="post">
                <input type="hidden" name="_method" value="PUT">
                @csrf
                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea style="min-height:300px" name="content" id="content" class="editor @error('content') is-invalid @enderror">{{@old('content',$pageblock->content)}}</textarea>
                    @error('content') 
                        <span class="invalid-feedback">
                            {{$message}}
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                 <button type="submit" class="btn btn-success ">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/invites/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="py-4"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="float-right">
                <a href="#invite-add-modal" data-target="#invite-add-modal" data-toggle="modal" class="btn btn-dark btn-sm">Add Invites</a>
            </div>
            <h4 class="text-primary">Free Access Invitations</h4>
            <p class="text-justify about-para">
                @empty($invites->count())
                <div class="text-center py-4 text-black-50">
                    <i class="fas fa-history fa-3x mb-3"></i>
                    <h3 class="mb-4">No Invites</h3>
                    <a href="#invite-add-modal" data-target="#invite-add-modal" data-toggle="modal" class="btn btn-dark btn-sm">Add Invites</a>
                </div>
                @else
                <table class="table table-sm">
                    <thead class="">
                        <th>Invite ID</th>
                        <th>Invite Email</th>
                        <th>Status</th>
                    </thead>
                    <tbody>
                        @foreach ($invites as $invite)
                            <tr>
                                <td><a href="{{route('invites.show',$invite)}}">{{$invite->id}}</a></td>
                                <td><a href="{{route('invites.show',$invite)}}">{{$invite->user_email}}</a></td>
                                <td><a href="{{route('invites.show',$invite)}}">{{$invite->is_accepted()}}</a></td>
                                <td><a href="{{route('invites.show',$invite)}}">{{$invite->user}}</a></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                @endempty                
                {{-- {{$invites->links}} --}}
            </p>
        </div>
    </div>
</div>
<div class="modal border-0" id="invite-add-modal" tabindex="-1" role="dialog" aria-labelledby="invite-add-modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered border-0" role="document">
    <div class="modal-content border-0">
      <div class="modal-header border-0">
        <h5 class="modal-title" id="invite-add-modalLabel">Add Email Addresses</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{route('invites.store')}}" method="POST">
            @csrf
            <label for="emails">Add Email Addresses Sperated by Commas</label>
            <textarea class="form-control" name="emails" id="emails" value="{{old('emails')}}"></textarea>
            <div class="py-3"></div>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Continue</button>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection