routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "HomeController@index");
Auth::routes(['verify' => true]);

Route::get('/page/{page}', "HomeController@page")->name('pages');
Route::any('/purchase', 'HomeController@Purchase')->name('purchase');
Route::get('/payment/confirm', 'PaymentController@index')->name('payment.confirm')->middleware('auth');
Route::post('/payment/process', 'PaymentController@process')->name('payment.process')->middleware('auth');
Route::post('/payment/invitation', 'PaymentController@invitation')->name('payment.invitation')->middleware('auth');
Route::get('/payment/confirmation', 'PaymentController@confirmation')->name('payment.confirmation')->middleware('auth');

Route::middleware(['subscribed','auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/access-videos', 'HomeController@access')->name('access-videos');
    Route::get('/access-video/{id}', 'HomeController@accessVideo')->name('access-video');
});

Route::prefix('admin')->group(function(){
    Route::get('', 'AdminController@index');
    Route::resource('page-blocks', 'PageBlockController');
    Route::resource('invites', 'InviteController');
    Route::resource('modules', 'Admin\VideoController');
    Route::resource('users', 'UserController');
    Route::resource('transactions', 'TransactionController');
    Route::resource('activity', 'ActivityController');
    Route::post('complete/activity/{activity}', 'ActivityController@complete')->name('activity.complete');
});

app/Video.php
<?php

namespace App;
use FFMpeg;
use Illuminate\Database\Eloquent\Model;

class Video extends Model
{

    public function FileDetails($atte)
    {
        // return FFMpeg::fromDisk('public')->open($this->video);
        return FFMpeg::fromDisk('public')->open($this->video)->getStreams()->first()->get($atte);
    }

    public function getDurationAttribute()
    {
        $media = FFMpeg::fromDisk('public')
                        ->open($this->video)
                        ->getStreams()
                        ->first()
                        ->get('duration');

        return gmdate("H:i:s", (int)$media);    
    }
}

app/Http/Controllers/Admin/VideoController.php
<?php

namespace App\Http\Controllers\Admin;

use FFMpeg;
use Storage;
use App\Video;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $videos = Video::orderBy('position','asc')->paginate(($request->count)?$request->count:10);
        return view('admin.videos.index',['videos'=>$videos]);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.videos.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "video"=>"required|file|",
            "title"=>"required|max:255|",
            "description"=>"required|string",
            "activity"=>"required|string",
            "position"=>"required|min:1",
            "thumbnail"=>"nullable|file",
            "create_at"=>"nullable|int|min:1",
        ]);
        $video = new Video;
        $filename = uniqid();
        $savedOriginal      = $request->file('video')->store('videos','public');
        $video->video       = $savedOriginal;
        // $video->video       = FFMpeg::fromDisk('public')->open($savedOriginal)->export()->inFormat(new FFMpeg\Format\Video\WebM)->save($filename.'.webm');
        // Storage::disk('public')->delete($savedOriginal);
        if($request->hasFile('thumbnail')){
            $video->thumbnail       = $request->file('thumbnail')->store('videos','public/thumbnails');
        }
        else{
            FFMpeg::fromDisk('public')
            ->open($video->video)
            ->getFrameFromSeconds($request->create_at)
            ->export()
            ->toDisk('public')
            ->save("thumbnails/$filename.png");
            $video->thumbnail = "thumbnails/$filename.png";
        }

        $video->title       = $request->title;
        $video->description = $request->description;
        $video->activity    = $request->activity;
        $video->position    = $request->position;
        $video->save();
        return redirect()->route('modules.index')->with('success',"New Module Attached");

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function show($video)
    {
        $video = Video::findorfail($video);
        return view('admin.videos.edit',['video'=>$video]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function edit(Video $video)
    {
        return view('admin.videos.edit',['video'=>$video]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $video)
    {
        $video = Video::findorfail($video);
        $request->validate([
            "title"=>"required|max:255|",
            "description"=>"required|string",
            "activity"=>"required|string",
            "position"=>"required|min:1",
            "thumbnail"=>"nullable|file",
            "create_at"=>"nullable|int|min:0",
        ]);
        if($request->hasFile('thumbnail')){
            Storage::delete($video->thumbnail);
            $video->thumbnail       = $request->file('thumbnail')->store('videos','public/thumbnails');
        }
        elseif($request->create_at >= 1){
            Storage::delete($video->thumbnail);
            FFMpeg::fromDisk('public')
            ->open($video->video)
            ->getFrameFromSeconds($request->create_at)
            ->export()
            ->toDisk('public')
            ->save("thumbnails/$video->video.png");
            $video->thumbnail = "thumbnails/$video->video.png";
        }

        $video->title       = $request->title;
        $video->description = $request->description;
        $video->activity    = $request->activity;
        $video->position    = $request->position;
        $video->save();
        return redirect()->route('modules.index')->with('success',"Module Edited");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function destroy($video)
    {
        $video = Video::findorfail($video);
        Storage::disk('public')->delete($video->video);
        Storage::disk('public')->delete($video->thumbnail);
        $video->delete();
        return redirect()->route('modules.index')->with('success',"Module Deleted");
    }
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Video;
use Illuminate\Http\Request;

class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function show(Video $video)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function edit(Video $video)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Video $video)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function destroy(Video $video)
    {
        //
    }
}

resources/views/admin/videos/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="jumbotron bg-primary text-white py-4">
    <div class="container">
        <div class="float-right">
            <a href="{{route('modules.index')}}" class="btn btn-outline-light btn-sm">Back to All </a>
        </div>
        <h4>Upload New Module</h4>
    </div>
</div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-10">
            <div class="card shadow-sm border-0">
                <div class="card-body">
                    <form action="{{route('modules.store')}}" method="post" enctype="multipart/form-data" class="row">
                        @csrf
                        <div class="form-group col-sm-12 col-md-12">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="video" name="video"  accept="video/*">
                                <label class="custom-file-label" for="video">Choose file</label>
                            </div>                            
                        </div>
                        <div class="col-sm-12"></div>
                        <div class="form-group col-sm-12 col-md-5">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="thumbnail"  name="thumbnail"  accept="image/*">
                                <label class="custom-file-label" for="thumbnail">Select Thumbnail</label>
                            </div>                            
                        </div>
                        <div class="form-group col-sm-12 col-md-1 py-2 text-center">
                            <strong>OR</strong>
                        </div>
                        <div class="form-group col-sm-12 col-md-6">
                            <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Create Thumbnail At</span>
                            </div>
                            <input type="number" name="create_at" id="create_at" class="form-control" min="1" value="{{old('create_at',10)}}" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Seconds</span>
                            </div>                            
                            </div>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="title">Video Title</label>
                            <input type="text" name="title" id="title" class="form-control" value="{{old('title')}}">
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="description">Description</label>
                            <textarea name="description" id="description" class="editor">{{old('description')}}</textarea>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="activity">Activity</label>
                            <textarea name="activity" id="activity" class="editor">{{old('activity')}}</textarea>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="position">Position</label>
                            <input type="number" step="1" min="1" name="position" id="position" class="form-control" value="{{old('position',1)}}"/>
                        </div>
                        <div class="form-group col-sm-12">
                            <button class="btn btn-primary" type="submit">Save and Continue</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/videos/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="jumbotron bg-primary text-white py-4">
    <div class="container">
        <div class="float-right">
            <a href="{{route('modules.index')}}" class="btn btn-outline-light btn-sm">Back to All </a>
        </div>
        <h4>Edit {{$video->title}}</h4>
    </div>
</div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-10">
            <div class="card shadow-sm border-0">
                <div class="card-body">
                    <form action="{{route('modules.update',$video)}}" method="post" enctype="multipart/form-data" class="row">
                        <input type="hidden" name="_method" value="put">                        
                        @csrf
                        <div class="col-sm-12"></div>
                        <div class="form-group col-sm-12 col-md-5">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="thumbnail"  name="thumbnail"  accept="image/*">
                                <label class="custom-file-label" for="thumbnail">Select Thumbnail</label>
                            </div>                            
                        </div>
                        <div class="form-group col-sm-12 col-md-1 py-2 text-center">
                            <strong>OR</strong>
                        </div>
                        <div class="form-group col-sm-12 col-md-6">
                            <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Create Thumbnail At</span>
                            </div>
                            <input type="number" name="create_at" id="create_at" class="form-control" min="0" value="{{old('create_at',0)}}" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Seconds</span>
                            </div>                            
                            </div>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="title">Video Title</label>
                            <input type="text" name="title" id="title" class="form-control" value="{{old('title',$video->title)}}">
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="description">Description</label>
                            <textarea name="description" id="description" class="editor">{{old('description',$video->description)}}</textarea>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="activity">Activity</label>
                            <textarea name="activity" id="activity" class="editor">{{old('activity',$video->activity)}}</textarea>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="position">Position</label>
                            <input type="number" step="1" min="1" name="position" id="position" class="form-control" value="{{old('position',$video->position)}}"/>
                        </div>
                        <div class="form-group col-sm-12">
                            <button class="btn btn-primary" type="submit">Save and Continue</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/videos/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="jumbotron bg-primary text-white py-4">
    <div class="container">
        <div class="float-right">
            <a href="{{route('modules.create')}}" class="btn btn-outline-light btn-sm">Upload New Video </a>
        </div>
        <h4>Modules</h4>
    </div>
</div>
<div class="container">
    <div class="row">
        @foreach ($videos as $video)
        <div class="col-sm-12 col-md-6 col-lg-4">
            <a href="{{route('modules.show',$video)}}">
            <div class="card mb-2 border-0 shadow-sm">
                <div class="img-thumbnail" style="background-image:url('{{Storage::url($video->thumbnail)}}')"></div>
                <div class="card-body">
                    {{$video->title}}
                </div>
                <div class="card-footer border-0">
                    <form action="{{route('modules.destroy',$video)}}" method="post">
                        <input type="hidden" name="_method" value="DELETE">
                        @csrf
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </div>
            </div>
            </a>
        </div>
        @endforeach
    </div>
        @empty($videos->count())
        No Videos
        @endempty
    {{$videos->links()}}
</div>
@endsection