routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "HomeController@index");
Auth::routes(['verify' => true]);

Route::get('/page/{page}', "HomeController@page")->name('pages');
Route::any('/purchase', 'HomeController@Purchase')->name('purchase');
Route::get('/payment/confirm', 'PaymentController@index')->name('payment.confirm')->middleware('auth');
Route::post('/payment/process', 'PaymentController@process')->name('payment.process')->middleware('auth');
Route::post('/payment/invitation', 'PaymentController@invitation')->name('payment.invitation')->middleware('auth');
Route::get('/payment/confirmation', 'PaymentController@confirmation')->name('payment.confirmation')->middleware('auth');

Route::middleware(['subscribed','auth'])->group(function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/access-videos', 'HomeController@access')->name('access-videos');
    Route::get('/access-video/{id}', 'HomeController@accessVideo')->name('access-video');
});

Route::prefix('admin')->group(function(){
    Route::get('', 'AdminController@index');
    Route::resource('page-blocks', 'PageBlockController');
    Route::resource('invites', 'InviteController');
    Route::resource('modules', 'Admin\VideoController');
    Route::resource('users', 'UserController');
    Route::resource('transactions', 'TransactionController');
    Route::resource('activity', 'ActivityController');
    Route::post('complete/activity/{activity}', 'ActivityController@complete')->name('activity.complete');
});

app/PageBlock.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PageBlock extends Model
{
    //
}

app/Http/Controllers/PageBlockController.php
<?php

namespace App\Http\Controllers;

use App\PageBlock;
use Illuminate\Http\Request;

class PageBlockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $pageBlocks = PageBlock::paginate(($request->count)?$request->count:10);
        return view('admin.pageblocks.index',['pageblocks'=>$pageBlocks]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pageblocks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "title"=>"required|string|max:255|unique:page_blocks",
            "content"=>"required|string",
        ]);
        $page = new PageBlock;
        $page->title = $request->title;
        $page->content = $request->content;
        $page->save();
        return redirect()->back()->with('success',"New Page Block Created");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PageBlock  $pageBlock
     * @return \Illuminate\Http\Response
     */
    public function show(PageBlock $pageBlock)
    {
        return view('admin.pageblocks.edit',['pageblock'=>$pageBlock]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PageBlock  $pageBlock
     * @return \Illuminate\Http\Response
     */
    public function edit(PageBlock $pageBlock)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PageBlock  $pageBlock
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PageBlock $pageBlock)
    {
        $request->validate([
            "content"=>"required|string",
        ]);
        $pageBlock->content = $request->content;
        $pageBlock->save();
        return redirect()->back()->with('success',"Page Block Updated");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PageBlock  $pageBlock
     * @return \Illuminate\Http\Response
     */
    public function destroy(PageBlock $pageBlock)
    {
        //
    }
}

resources/views/admin/pageblocks/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="py-4"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="float-right">
                <a href="{{route('page-blocks.index')}}" class="btn btn-dark btn-sm">Back to Pageblocks</a>
            </div>
            <h4>Create Page Block</h4>
        </div>
        <div class="col-sm-12 mt-4">
            <form action="{{route('page-blocks.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="title">Slug</label>
                    <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror" value="{{@old('title')}}">
                    @error('title') 
                        <span class="invalid-feedback">
                            {{$message}}
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea name="content" id="content" class="editor @error('content') is-invalid @enderror">{{@old('content')}}</textarea>
                    @error('content') 
                        <span class="invalid-feedback">
                            {{$message}}
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                 <button type="submit" class="btn btn-success ">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/pageblocks/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="jumbotron bg-primary text-white py-4">
    <div class="container">
        <div class="float-right">
            <a href="{{route('page-blocks.index')}}" class="btn btn-outline-light btn-sm">Back to Pageblocks</a>
        </div>
        <h4>Edit {{$pageblock->title}}</h4>
    </div>
</div>
<div class="container">
        <div class="col-sm-12 mt-4">
            <form action="{{route('page-blocks.update',$pageblock)}}" method="post">
                <input type="hidden" name="_method" value="PUT">
                @csrf
                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea style="min-height:300px" name="content" id="content" class="editor @error('content') is-invalid @enderror">{{@old('content',$pageblock->content)}}</textarea>
                    @error('content') 
                        <span class="invalid-feedback">
                            {{$message}}
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                 <button type="submit" class="btn btn-success ">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/pageblocks/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="jumbotron bg-primary text-white py-4">
    <div class="container">
        <div class="float-right">
            <a href="{{route('page-blocks.create')}}" class="btn btn-outline-light btn-sm">Create new Block</a>
        </div>
        <h4>Page Blocks</h4>
    </div>
</div>
<div class="container">
    <div class="row">
        @foreach ($pageblocks as $pageblock)
        <div class="col-sm-12 col-md-6 col-lg-4">
            <a href="{{route('page-blocks.show',$pageblock)}}">
            <div class="card mb-2 border-0 shadow-sm">
                <div class="card-body">
                    {{$pageblock->title}}
                </div>
            </div>
            </a>
        </div>
        @endforeach
    </div>
        @empty($pageblocks->count())
        No Page Blocks Available
        @endempty
    {{$pageblocks->links()}}
</div>
@endsection